apiVersion: v1
kind: Pod
metadata:
  name: deb
  namespace: magasin
spec:
  containers:
  - name: debian-container
    image: debian:latest
    command: ["/bin/sleep", "infinity"]  # Keep the container running
