on:
  workflow_dispatch:

name: Test installer

jobs:
  run-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Requirements - all missing
        run: |
            ls -la 
            cd scripts/installer
            ./install-magasin.sh -c
            
            
