on:
  workflow_dispatch:

name: Test installer

jobs:
  run-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Requirements - all missing
        run: |
            ls -la 
            cd scripts/installer
            ./install-magasin.sh -c
            
  run-macos:
    runs-on: macos-latest  # Specifies the macOS runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Action to checkout your repository's code

    - name: Run a macOS command
      run: |
        ls -la 
        cd scripts/installer
        ./install-magasin.sh -c
           