#
# https://quarto.org/docs/publishing/github-pages.html#publish-action
#
on:
  workflow_dispatch:
  push:
    branches: main

name: Publish web docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      
      # Because index.yaml is not part of the documentation
      # We need to get the latest version from gh-pages 
      # And copy it to the docs/www folder.
      
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      
      - name: Copy index.yaml
        run: |
          ls gh-pages
          ls docs/*
          cp gh-pages/index.yaml  docs/www/index.yaml
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
